//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionabcense
{
    using System;
    using System.Collections.Generic;
    
    public partial class Decision
    {
        public int numrestifsar { get; set; }
        public Nullable<System.DateTime> datestifdsar { get; set; }
        public string service { get; set; }
        public Nullable<int> jourdeduirr { get; set; }
        public Nullable<System.DateTime> datededure { get; set; }
        public Nullable<int> iddes { get; set; }
        public string typedecision { get; set; }
        public Nullable<int> numdesisionktita3 { get; set; }
    
        public virtual absence absence { get; set; }
    }
}
