//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionabcense
{
    using System;
    using System.Collections.Generic;
    
    public partial class detaille_abs
    {
        public int iddetaile { get; set; }
        public string irsalistifsar { get; set; }
        public Nullable<System.DateTime> dateirsalistifsar { get; set; }
        public string reponsestifsar { get; set; }
        public string wosolistifsar { get; set; }
        public Nullable<System.DateTime> datereponsestifsar { get; set; }
        public string  typedereponse{ get; set; }

        
        public Nullable<int> idabs { get; set; }
    
        public virtual absence absence { get; set; }
    }
}
