//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionabcense
{
    using System;
    using System.Collections.Generic;
    
    public partial class usere
    {
        public string username { get; set; }
        public int password { get; set; }
        public Nullable<bool> adminn { get; set; }
    }
}
